### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by onkelfarmor** [trympet/homebridge-volvo#3]
How do I install this in Homebridge?

**Comment by DJay-X** [comment]
@trympet Thanks for your work.
I understand that your plugin is not available via npm? Is there a reason for this? npm would be more practical, of course, since it can be installed via config-ui-x, among others.

@onkelfarmor At the moment you have to use terminal and
`sudo npm install -g git+https://github.com/trympet/homebridge-volvo.git`
At least this was the way I tried.

You have a fanbase already @trympet  😉👍

**Comment by onkelfarmor** [comment]
@DJay-X tried the same and got the same error.
@trympet we really want to try homebridge-volvo!

**Comment by trympet** [comment]
Hey guys. I published to npm just now. Will update readme and config example by the end of the day, as well as create a schema for config-ui-x 😎. You can install using: `npm install -g homebridge-volvo`. Please keep me posted if any issues arise.
